name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
            - dev
    push:
        branches:
            - delete-trip
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: install dependencies
              run: npm install

            - name: run Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2

            - name: codecov coverage report
              uses: codecov/codecov-action@v2
              with:
                file: server/coverage/lcov.info
