name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - dev
jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
          checks: write
          actions: write
          contents: read
          pull-requests: write
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: install dependencies
              run: |
                cd server
                npm install

            - name: run Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2
