name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - dev
    push:
        branches:
            - delete-trip
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
          DB_URL: ${{ secrets.DB_URL }}
        permissions:
          checks: write
          actions: write
          contents: read
          pull-requests: write
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: install dependencies
              run: |
                cd server
                npm install

            - name: run Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2

            - name: codecov coverage report
              uses: codecov/codecov-action@v2
              with:
                file: server/coverage/lcov.info
